{% set name = "pipda" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipda-{{ version }}.tar.gz
  sha256: d3c496615d45fff6dfa8255b48070b9be619bfe35e94ead5e9200f73f507d0ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - diot
    - executing
    - pure_eval <1.0.0
    - python >=3.6
    - varname

test:
  imports:
    - pipda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/pipda
  doc_url: https://pwwang.github.io/pipda/api/pipda/
  summary: A framework for data piping in python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
