{% set name = "pipda" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipda-{{ version }}.tar.gz
  sha256: 01c4891728f49fc1145709bfa456b2678f0bc0fa438d0a3e0f22f466a514a7a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.7,<4.0
  run:
    - executing <2.0.0,>=1.1.1
    - python >=3.7,<4.0

test:
  imports:
    - pipda
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/pipda
  doc_url: https://pwwang.github.io/pipda/api/pipda/
  summary: A framework for data piping in python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
