{% set name = "pipda" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pipda-{{ version }}.tar.gz
  sha256: 56420cbb285a085db385a37ad267f59ba090ec1e901eb122132bd64ad5f515f9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python {{ python_min }}
  run:
    - executing >=2.0,<3.0
    - python >={{ python_min }},<4.0.0

test:
  imports:
    - pipda
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pwwang/pipda
  doc_url: https://pwwang.github.io/pipda/api/pipda/
  summary: A framework for data piping in python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
